<?php

return [
    'enabled' => false,
    'hide_empty_tabs' => true,
    'except' => [
        'telescope*',
        'horizon*',
    ],
    'storage' => [
        'enabled' => false,
        'open' => false,
        'driver' => 'file',
        'path' => storage_path('debugbar'),
        'connection' => null,
        'provider' => '',
        'hostname' => '127.0.0.1',
        'port' => 2304,
    ],
    'editor' => 'phpstorm',
    'remote_sites_path' => null,
    'local_sites_path' => null,
    'include_vendors' => true,
    'capture_ajax' => false,
    'add_ajax_timing' => false,
    'ajax_handler_auto_show' => false,
    'ajax_handler_enable_tab' => false,
    'defer_datasets' => false,
    'error_handler' => false,
    'clockwork' => false,
    'collectors' => [
        'phpinfo' => false,
        'messages' => false,
        'time' => false,
        'memory' => false,
        'exceptions' => false,
        'log' => false,
        'db' => false,
        'views' => false,
        'route' => false,
        'auth' => false,
        'gate' => false,
        'session' => false,
        'symfony_request' => false,
        'mail' => false,
        'laravel' => false,
        'events' => false,
        'default_request' => false,
        'logs' => false,
        'files' => false,
        'config' => false,
        'cache' => false,
        'models' => false,
        'livewire' => false,
        'jobs' => false,
        'pennant' => false,
    ],
    'options' => [
        'time' => [
            'memory_usage' => false,
        ],
        'messages' => [
            'trace' => false,
            'capture_dumps' => false,
        ],
        'memory' => [
            'reset_peak' => false,
            'with_baseline' => false,
            'precision' => 0,
        ],
        'auth' => [
            'show_name' => false,
            'show_guards' => false,
        ],
        'gate' => [
            'trace' => false,
        ],
        'db' => [
            'with_params' => false,
            'exclude_paths' => [],
            'backtrace' => false,
            'backtrace_exclude_paths' => [],
            'timeline' => false,
            'duration_background' => false,
            'explain' => [
                'enabled' => false,
            ],
            'hints' => false,
            'show_copy' => false,
            'slow_threshold' => false,
            'memory_usage' => false,
            'soft_limit' => 100,
            'hard_limit' => 500,
        ],
        'mail' => [
            'timeline' => false,
            'show_body' => false,
        ],
        'views' => [
            'timeline' => false,
            'data' => false,
            'group' => 50,
            'inertia_pages' => 'js/Pages',
            'exclude_paths' => [
                'vendor/filament'
            ],
        ],
        'route' => [
            'label' => false,
        ],
        'session' => [
            'hiddens' => [],
        ],
        'symfony_request' => [
            'label' => false,
            'hiddens' => [],
        ],
        'events' => [
            'data' => false,
            'excluded' => [],
        ],
        'logs' => [
            'file' => null,
        ],
        'cache' => [
            'values' => false,
        ],
    ],
    'inject' => false,
    'route_prefix' => '_debugbar',
    'route_middleware' => [],
    'route_domain' => null,
    'theme' => 'auto',
    'debug_backtrace_limit' => 50,
];
